# Generated by Django 4.1.1 on 2022-11-17 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='administrator',
            options={'permissions': (('admin_things', 'All thing that admin can do'),)},
        ),
    ]
