# Generated by Django 4.1.1 on 2022-11-20 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0002_alter_administrator_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='administrator',
            options={'permissions': (('admin_things', 'All the things that only admin can do'),)},
        ),
    ]
