# Generated by Django 4.1.1 on 2022-11-17 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='specialist',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
