# Generated by Django 4.1.1 on 2022-11-20 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_alter_doctor_description_alter_doctor_specialist'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctor',
            options={'permissions': (('doctor_things', 'All the things that only doctor can do'),)},
        ),
    ]
