# Generated by Django 4.1.1 on 2022-11-18 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='doc_comment',
            field=models.CharField(default=' ', max_length=1000),
            preserve_default=False,
        ),
    ]
